##
# Linters
##

##
# Mypy
[tool.mypy]
check_untyped_defs = true
ignore_missing_imports = false
strict = true
warn_no_return = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = "ansible_collections.benschubert.infrastructure.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "ansible.module_utils.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "testinfra.*"
ignore_missing_imports = true

##
# Pylint
[tool.pylint.basic]
good-names = ["pk"]

[tool.pylint.messages_control]
disable = [
    # Taken care of by ruff
    "fixme",
    "import-error",
    "inconsistent-return-statements",
    "invalid-name",
    "line-too-long",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
    "redefined-builtin",
    "redefined-outer-name",
    "too-few-public-methods",
    "too-many-arguments",
    "too-many-positional-arguments",
    "unused-argument",
    "wrong-import-position",
    # Duplicate code can't be disabled on a per problem basis
    "duplicate-code",
]

[tool.pylint.variables]
init-import = true

##
# Ruff
[tool.ruff]
target-version = "py311"
line-length = 79

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN401",  # Allow using Any as typing
    "COM812",  # Otherwise conflicts with the formatter
    "D104",  # Don't force documenting packages
    "D107",  # Don't document __init__
    "D203",  # No blank line before class docstrings
    "D212",  # Start docstring on second line
    "D404",  # Allow more freeform documentation
    "FBT001",  # Allow non-kwonly booleans
    "FBT002",  # Allow non-kwonly booleans
    "FIX001",  # Allow fixmes
    "S101",  # Allow asserts
    "SIM108",  # Don't force ternary operators if something else is more readable
    "TD",  # Don't force format in FIXMEs
]

pycodestyle.max-line-length = 119
pylint.max-args = 7

[tool.ruff.lint.per-file-ignores]
"docs/*" = [
    "D",  # Don't require docs for tests
    "INP001",  # No explicit packages here
]
"molecule/default/tests/*" = [
    "D",  # Don't require docs for tests
    "T201",  # Allow print for debugs
]
"plugins/modules/*" = [
    "D100",  # Documentation in Ansible is under DOCUMENTATION=
    "D103",  # Don't force documentation of public methods
    "E402",  # Imports are not top level for ansible modules
]
"plugins/doc_fragments/*" = [
    "D",  # No documentation
]


##
# Tests
##
[tool.pytest.ini_options]
addopts = "--color=yes --verbose --verbose"

filterwarnings = [
    "error",
    "ignore:.*to host 'localhost'.*:urllib3.exceptions.InsecureRequestWarning"
]
