---
- name: Create container instances
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ensure required directories exist
      ansible.builtin.file:
        path: "{{ molecule_ephemeral_directory }}/{{ item }}"
        state: directory
        mode: "0o755"
      loop:
        - keys
        - cloud-init

    - name: Generate a ssh key
      community.crypto.openssh_keypair:
        path: "{{ molecule_ephemeral_directory }}/keys/id_rsa"
      register: _key

    - name: Generate cloud-init user config
      ansible.builtin.copy:
        content: |
          #cloud-config
          disable: true
          hostname: molecule-benschubert-infrastructure
          fqdn: ansible.benschubert.infrastructure
          manage_etc_hosts: true
          users:
            - name: testuser
              ssh-authorized-keys:
                - {{ _key.public_key }}
              sudo: ['ALL=(ALL) NOPASSWD:ALL']
              groups: sudo
              shell: /bin/bash
          ssh_pwauth: false
          disable_root: true
          runcmd:
            - apt-get update
            - apt-get install --assume-yes qemu-guest-agent
            - systemctl enable --now qemu-guest-agent
        dest: "{{ molecule_ephemeral_directory }}/cloud-init/user-data"
        mode: "0o644"

    - name: Generate cloud-init iso
      ansible.builtin.command:
        cmd: >-
          cloud-localds
            {{ molecule_ephemeral_directory }}/cloud-init/cloud-init.iso
            {{ molecule_ephemeral_directory }}/cloud-init/user-data
        creates: "{{ molecule_ephemeral_directory }}/cloud-init/cloud-init.iso"

    - name: Download the Debian base image
      ansible.builtin.get_url:
        url: https://cloud.debian.org/images/cloud/trixie/latest/debian-13-genericcloud-amd64.qcow2
        dest: "{{ molecule_ephemeral_directory | dirname }}/original-debian-13.qcow2"
        mode: "0o644"
        checksum: sha512:https://cloud.debian.org/images/cloud/trixie/latest/SHA512SUMS

    - name: Copy the pre-downloaded image
      ansible.builtin.copy:
        src: "{{ molecule_ephemeral_directory | dirname }}/original-debian-13.qcow2"
        dest: "{{ molecule_ephemeral_directory }}/disk.qcow2"
        mode: "0o644"
        force: false

    - name: Expand the disk
      ansible.builtin.command:
        cmd: qemu-img resize {{ molecule_ephemeral_directory }}/disk.qcow2 10G
      changed_when: true

    - name: Start the VM
      community.libvirt.virt_install:
        name: molecule-benschubert-infrastructure-test
        memory: 8192
        vcpus: 4
        cdrom: "{{ molecule_ephemeral_directory }}/cloud-init/cloud-init.iso"
        disks:
          - path: "{{ molecule_ephemeral_directory }}/disk.qcow2"
        import: true
        graphics:
          type: spice
        networks:
          - bridge: virbr0
            model:
              type: virtio
        osinfo:
          name: debian13
        transient: false
        uri: qemu:///session
        virt_type: kvm

    - name: Recover the VM connection information
      ansible.builtin.command:
        cmd: >-
          virsh
            qemu-agent-command
            molecule-benschubert-infrastructure-test
            '{"execute":"guest-network-get-interfaces"}'
      changed_when: false
      register: _vm
      retries: 30
      delay: 2

    - name: Dump instance config
      ansible.builtin.copy:
        content: |
          # Molecule managed
          ---
          all:
            children:
              molecule:
                hosts:
                  molecule-benschubert-infrastructure:
                    ansible_host: {{
                      (_vm.stdout | from_json).return[1]['ip-addresses'][0]['ip-address']
                    }}
                    ansible_user: testuser
                    ansible_ssh_private_key_file: {{ molecule_ephemeral_directory }}/keys/id_rsa
        dest: "{{ molecule_scenario_directory }}/inventory/autogenerated.yml"
        mode: "0600"

    - name: Dump instance config
      ansible.builtin.copy:
        content: |
          # Molecule managed
          ---
          - instance: molecule-benschubert-infrastructure
            address: {{ (_vm.stdout | from_json).return[1]['ip-addresses'][0]['ip-address'] }}
            identity_file: {{ molecule_ephemeral_directory }}/keys/id_rsa
            port: 22
            user: testuser
        dest: "{{ molecule_instance_config }}"
        mode: "0600"

    - name: Poweroff the vm
      community.libvirt.virt:
        name: molecule-benschubert-infrastructure-test
        state: shutdown
        uri: qemu:///session

    - name: Wait for the VM to be off
      community.libvirt.virt:
        name: molecule-benschubert-infrastructure-test
        command: status
        uri: qemu:///session
      until: _vm_stat.status == "shutdown"
      retries: 10
      delay: 1
      register: _vm_stat

    - name: Reboot the vm
      community.libvirt.virt:
        name: molecule-benschubert-infrastructure-test
        state: running
        uri: qemu:///session

    - name: Wait for the VM to come back online
      ansible.builtin.wait_for:
        host: "{{ (_vm.stdout | from_json).return[1]['ip-addresses'][0]['ip-address'] }}"
        port: 22
