---
- name: Create container instances
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Start Virtual machine
      ansible.builtin.command:
        cmd: vagrant up
      changed_when: "'Machine already provisioned.' not in _vagrant_up.stdout"
      register: _vagrant_up

    - name: Recover ssh config information
      ansible.builtin.command:
        cmd: vagrant ssh-config
      changed_when: false
      register: _vagrant_ssh

    - name: Dump instance config
      ansible.builtin.copy:
        content: |
          # Molecule managed
          ---
          all:
            children:
              molecule:
                hosts:
                  molecule-benschubert-infrastructure:
                    ansible_ssh_host: {{ _vagrant_ssh.stdout_lines | select('match', '^\s+HostName ') | first | trim | split(' ', 1) | last }}
                    ansible_user: vagrant
                    ansible_ssh_private_key_file: {{ _vagrant_ssh.stdout_lines | select('match', '^\s+IdentityFile ') | first | trim | split(' ', 1) | last }}
        dest: "{{ molecule_scenario_directory }}/inventory/autogenerated.yml"
        mode: "0600"
