---
ansible:
  cfg:
    ssh_connection:
      ssh_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
  executor:
    args:
      ansible_playbook:
        - --inventory=inventory/
  env:
    ANSIBLE_CALLBACKS_ENABLED: ansible.posix.profile_roles, ansible.posix.profile_tasks
    ANSIBLE_CALLBACK_RESULT_FORMAT: yaml
    ANSIBLE_DIFF_ALWAYS: "True"
    ANSIBLE_PIPELINING: "True"
    PROFILE_TASKS_SUMMARY_ONLY: "True"
    PROFILE_ROLES_SUMMARY_ONLY: "True"

dependency:
  name: galaxy
  options:
    requirements-file: ${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml

platforms:
  - name: molecule-benschubert-infrastructure

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: testinfra
  options:
    ansible-inventory: inventory/
