---
ingress_validate_certs: true
ingress_https_port: 443

auth_authentik_authentication_page_title: Welcome to {{ auth_authentik_hostname }}!
auth_authentik_branding_title: Authentik
# FIXME: keep this value up to date
auth_authentik_image: ghcr.io/goauthentik/server:2025.4
auth_authentik_superadmin_bootstrap_email: null
auth_authentik_superadmin_bootstrap_password: null
auth_authentik_superadmin_bootstrap_token: null
auth_authentik_token: "{{ auth_authentik_superadmin_bootstrap_token }}"
auth_monitor_agent_user_group: null
auth_worker_additional_networks: []
