FROM docker.io/debian:trixie-slim

ENV DEBIAN_FRONTEND=noninteractive

# Install required packages
RUN apt-get update && \
    apt-get upgrade --assume-yes && \
    apt-get install --assume-yes --no-install-recommends \
        aardvark-dns \
        bash \
        busybox-static \
        ca-certificates \
        catatonit \
        dbus-user-session \
        fuse-overlayfs \
        init \
        iproute2 \
        iptables \
        nftables \
        passt \
        podman \
        python3 \
        sudo \
        systemd \
        uidmap \
        # And some utilities to help debug
        curl \
        jq \
        less \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Configure users
RUN useradd --create-home --groups sudo --shell /bin/bash podman && \
    echo "podman:10000:65534" > /etc/subuid && \
    echo "podman:10000:65534" > /etc/subgid && \
    echo "%sudo ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/sudo && \
    # And create cacheable volume for the storage
    mkdir -p /home/podman/.local/share/containers && \
    chown -R podman:podman /home/podman/.local && \
    # And for the actual files
    mkdir -p /home/podman/infrastructure && \
    chown -R podman:podman /home/podman/infrastructure && \
    # Enable lingering of the session
    # Equivalent to loginctl enable-linger podman
    mkdir -p /var/lib/systemd/linger && \
    touch /var/lib/systemd/linger/podman

# Configure podman
COPY isolated_hosts /etc/isolated_hosts
COPY containers.conf /etc/containers/containers.conf
COPY --chown=podman:podman storage.conf /home/podman/.config/containers/storage.conf

VOLUME /home/podman/.local/share/containers
VOLUME /home/podman/infrastructure

CMD ["/usr/sbin/init"]
