---
all:
  children:
    molecule:
      hosts:
        molecule-benschubert-infrastructure:

          # Test optimisations
          registries_conf: "{{ lookup('ansible.builtin.env', 'REGISTRIES_CONF') or none }}"
          apt_proxy: "{{ lookup('ansible.builtin.env', 'APT_PROXY') or '' }}"

          hostnames:
            - "{{ auth_authentik_hostname }}"
            - "{{ ingress_traefik_dashboard_hostname }}"
            - "{{ monitoring_grafana_hostname }}"
            - "{{ monitoring_loki_hostname }}"
            - "{{ monitoring_mimir_hostname }}"
            - "{{ mailpit_test_gateway_mailpit_hostname }}"

          ##
          # Collection
          data: /srv/infrastructure

          template_warning: |
            ##################################################
            # WARNING
            #
            # This file is managed by ansible.
            #
            # Any change done on this file will be overriden
            # on the next run of ansible.
            ##################################################

          # Hostnames
          auth_authentik_hostname: >-
            {{ lookup('ansible.builtin.env', 'AUTHENTIK_HOSTNAME', default="auth.test") }}
          ingress_traefik_dashboard_hostname: >-
            {{ lookup('ansible.builtin.env', 'TRAEFIK_HOSTNAME', default="traefik.test") }}
          monitoring_grafana_hostname: >-
            {{ lookup('ansible.builtin.env', 'GRAFANA_HOSTNAME', default="grafana.test") }}
          monitoring_loki_hostname: >-
            {{ lookup('ansible.builtin.env', 'LOKI_HOSTNAME', default="loki.test") }}
          monitoring_mimir_hostname: >-
            {{ lookup('ansible.builtin.env', 'MIMIR_HOSTNAME', default="mimir.test") }}
          mailpit_test_gateway_mailpit_hostname: >-
            {{ lookup('ansible.builtin.env', 'MAILPIT_HOSTNAME', default="mailpit.test") }}

          # Networks
          ingress_additional_networks:
            - ingress-mailpit

          auth_worker_additional_networks:
            - auth-worker-mailpit

          monitoring_mimir_additional_networks:
            - monitoring-mimir-mailpit

          mailpit_test_gateway_networks:
            - ingress-mailpit
            - auth-worker-mailpit
            - monitoring-mimir-mailpit

          # Group membership
          default_monitor_agent_user_group: >-
            {{ lookup('ansible.builtin.env', 'MONITOR_AGENT_USER_GROUP') or none }}
          test_akadmin_user_group: >-
            {{ lookup('ansible.builtin.env', 'TEST_AKADMIN_USER_GROUP', default="Grafana Admins") }}
          monitoring_grafana_admin_group_name: >-
            {{
              lookup('ansible.builtin.env', 'GRAFANA_ADMIN_GROUP_NAME', default="Grafana Admins")
            }}

          ingress_traefik_allowlisted_groups: >-
            {{ lookup('ansible.builtin.env', 'TRAEFIK_ALLOWLISTED_GROUPS') | from_yaml }}
          monitoring_grafana_allowlisted_groups: >-
            {{ lookup('ansible.builtin.env', 'GRAFANA_ALLOWLISTED_GROUPS') | from_yaml }}
          monitoring_loki_allowlisted_groups: >-
            {{ lookup('ansible.builtin.env', 'LOKI_ALLOWLISTED_GROUPS') | from_yaml }}
          monitoring_mimir_allowlisted_groups: >-
            {{ lookup('ansible.builtin.env', 'MIMIR_ALLOWLISTED_GROUPS') | from_yaml }}
          mailpit_test_gateway_allowlisted_groups: >-
            {{ lookup('ansible.builtin.env', 'MAILPIT_ALLOWLISTED_GROUPS') | from_yaml }}

          ##
          # Ingress
          ##
          ingress_custom_ca_cert_url: >-
            {{ lookup('ansible.builtin.env', 'TRAEFIK_CUSTOM_CA_CERT') or none }}
          ingress_http_port: "{{ lookup('ansible.builtin.env', 'HTTP_PORT', default=80) }}"
          ingress_https_port: "{{ lookup('ansible.builtin.env', 'HTTPS_PORT', default=443) }}"
          ingress_monitor_agent_config_path: "{{ data }}/ingress/agent/config"
          ingress_monitor_agent_data_path: "{{ data }}/ingress/agent/data"
          ingress_traefik_certificates_resolvers: >-
            {{ lookup('ansible.builtin.env', 'TRAEFIK_CERTIFICATES_RESOLVER') | from_yaml }}
          ingress_traefik_configuration_files_path: "{{ data }}/ingress/traefik"
          ingress_traefik_environment_variables: >-
            {{ lookup('ansible.builtin.env', 'TRAEFIK_ENVIRONMENT_VARIABLES') | from_yaml }}
          ingress_traefik_secrets: >-
            {{ lookup('ansible.builtin.env', 'TRAEFIK_SECRETS') | from_yaml }}
          ingress_validate_certs: >-
            {{ lookup('ansible.builtin.env', 'TRAEFIK_VALIDATE_CERTS', default=false) }}

          ##
          # Auth
          ##
          auth_authentik_secret_key: verysecretkey
          auth_authentik_superadmin_bootstrap_email: >-
            {{ lookup('ansible.builtin.env', 'AUTHENTIK_EMAIL') or none }}
          auth_authentik_superadmin_bootstrap_password: password
          auth_authentik_superadmin_bootstrap_token: superadmintoken
          auth_monitor_agent_config_path: "{{ data }}/auth/agent/config"
          auth_monitor_agent_data_path: "{{ data }}/auth/agent/data"
          auth_postgres_password: verysecretpassword
          auth_postgres_data_path: "{{ data }}/auth/postgres"
          auth_authentik_configuration_path: "{{ data }}/auth/authentik"
          auth_authentik_email_config:
            host: mailpit
            port: 1025
            from: testing@github.com.benschubert.infrastructure
            username: mailpit
            password: mailpit-password
          auth_authentik_background: >-
            {{ lookup('ansible.builtin.env', 'AUTHENTIK_WALLPAPER') or none }}
          auth_authentik_icon: "{{ lookup('ansible.builtin.env', 'AUTHENTIK_ICON') or none }}"

          ##
          # Monitoring
          ##
          monitoring_grafana_secret_key: averysecretsecret
          monitoring_grafana_admin_user: admin
          monitoring_grafana_admin_bootstrap_password: supersecretpassword
          monitoring_grafana_postgres_password: postgresgrafanapassword
          monitoring_grafana_postgres_data_path: "{{ data }}/monitoring/grafana/postgres"
          monitoring_grafana_config_path: "{{ data }}/monitoring/grafana/config"
          monitoring_grafana_data_path: "{{ data }}/monitoring/grafana/data"
          monitoring_loki_config_path: "{{ data }}/monitoring/loki/config"
          monitoring_loki_data_path: "{{ data }}/monitoring/loki/data"
          monitoring_mimir_alertmanager_config_template: alertmanager-fallback-config.yml.j2
          monitoring_mimir_config_path: "{{ data }}/monitoring/mimir/config"
          monitoring_mimir_data_path: "{{ data }}/monitoring/mimir/data"
          monitoring_mimir_secrets:
            auth_password: mailpit-password
          monitoring_monitor_agent_config_path: "{{ data }}/monitoring/agent/config"
          monitoring_monitor_agent_data_path: "{{ data }}/monitoring/agent/data"

          ##
          # Mailpit for testing
          ##
          mailpit_test_gateway_smtp_username: mailpit
          mailpit_test_gateway_smtp_password: mailpit-password
