---
- name: Setup Grafana
  ansible.builtin.import_tasks:
    file: _grafana.yml

- name: Setup Mimir
  ansible.builtin.import_tasks:
    file: _mimir.yml

- name: Monitor the monitoring services
  ansible.builtin.import_role:
    name: monitoring
    tasks_from: agent
  vars:
    monitoring_agent_product_name: monitoring
    monitoring_agent_config_path: "{{ monitoring_monitor_agent_config_path }}"
    monitoring_agent_data_path: "{{ monitoring_monitor_agent_data_path }}"
    monitoring_agent_networks:
      - ingress-monitoring
      - monitoring-grafana-postgres
    monitoring_agent_pod: monitoring-monitor
    monitoring_agent_prometheus_endpoints:
      - name: mimir
        address: monitoring-mimir:9009
        alerting_rules_template: mimir-alerts.yml.j2
      - name: grafana
        address: monitoring-grafana:3000
    monitoring_agent_postgres_instances:
      - instance: monitoring-grafana-postgres
        username: grafana
        password: "{{ monitoring_grafana_postgres_password }}"
        database: grafana
    monitoring_agent_redis_instances: []
