---
- name: Create the mimir-grafana network
  containers.podman.podman_network:
    name: monitoring-grafana-mimir
    internal: true

- name: Setup Grafana
  ansible.builtin.import_tasks:
    file: _grafana.yml

- name: Setup Mimir
  ansible.builtin.import_tasks:
    file: _mimir.yml
