---
- name: Create an application for Traefik on authentik
  ansible.builtin.import_role:
    name: auth
    tasks_from: application
  vars:
    application_name: Traefik's dashboard
    application_slug: benschubert-infrastructure-traefik-dashboard
    group: admin
    meta_description: The dashboard for Traefik
    # yamllint disable-line rule:line-length
    icon_url: https://{{ ingress_traefik_dashboard_hostname }}:{{ ingress_https_port }}/dashboard/icons/favicon-32x32.png
    provider_proxy:
      hostname: "{{ ingress_traefik_dashboard_hostname }}"

- name: Setup a provider for the traefik dashboard
  ansible.builtin.import_role:
    name: benschubert.infrastructure.ingress
    tasks_from: provider
  vars:
    template_file: ingress-traefik-dashboard.yml.j2
    ingress_name: traefik-dashboard
    hostname: "{{ ingress_traefik_dashboard_hostname }}"
    expected_status_code: 302

- name: Configure the Alloy image if not provided explicitly
  ansible.builtin.set_fact:
    ingress_monitor_agent_alloy_image: "{{ monitoring_agent_alloy_image }}"
  when: ingress_monitor_agent_alloy_image is not defined

- name: Monitor Traefik
  ansible.builtin.import_role:
    name: monitoring
    tasks_from: agent
  vars:
    monitoring_agent_product_name: ingress
    monitoring_agent_config_path: "{{ ingress_monitor_agent_config_path }}"
    monitoring_agent_data_path: "{{ ingress_monitor_agent_data_path }}"
    monitoring_agent_alloy_image: "{{ ingress_monitor_agent_alloy_image }}"
    monitoring_agent_networks:
      - ingress
    monitoring_agent_pod: ingress-monitor
    monitoring_agent_prometheus_endpoints:
      - name: traefik
        address: ingress:8082
        alerting_rules_template: traefik-alerts.yml.j2
    monitoring_agent_postgres_instances: []
    monitoring_agent_redis_instances: []
