---
- name: Create the provider configuration for Traefik for {{ ingress_name }}
  become: true
  ansible.builtin.template:
    src: "{{ template_file }}"
    dest: >-
      {{ ingress_traefik_configuration_files_path }}/config/providers/{{ ingress_name }}.yml
    mode: "0o400"

- name: Wait until the service is accessible for {{ ingress_name }}
  block:
    - name: Wait until the service is accessible
      ansible.builtin.uri:
        url: https://{{ hostname }}{{
            "" if ingress_https_port == 443 else ":{}".format(ingress_https_port)
          }}/
        ca_path: "{{ ingress_custom_ca_cert | default(omit) }}"
        validate_certs: "{{ ingress_validate_certs }}"
        follow_redirects: none
      register: _service
      failed_when: _service.status == -1
      until: _service.status != -1
      retries: 15
      delay: 2
  rescue:
    - name: Restart the ingress service in case it's a problem generating the certificate
      become: true
      ansible.builtin.systemd:
        name: ingress
        state: restarted

    - name: Wait again until the service is accessible
      ansible.builtin.uri:
        url: https://{{ hostname }}{{
            "" if ingress_https_port == 443 else ":{}".format(ingress_https_port)
          }}/
        ca_path: "{{ ingress_custom_ca_cert | default(omit) }}"
        validate_certs: "{{ ingress_validate_certs }}"
        follow_redirects: none
      register: _service
      until: _service.status != -1
      retries: 10
      delay: 2
