---
- name: Converge
  hosts: all
  gather_facts: false

  tasks:
    - name: Download and setup custom certificate
      when: ingress_custom_ca_cert_url | default(False)
      block:
        - name: Set the path to the custom ca
          ansible.builtin.set_fact:
            ingress_custom_ca_cert: /tmp/custom_ca_cert.pem

        - name: Download custom CA
          ansible.builtin.uri:
            url: "{{ ingress_custom_ca_cert_url }}"
            dest: "{{ ingress_custom_ca_cert }}"
            status_code:
              - 200
              - 304
          tags:
            - molecule-idempotence-notest

    # FIXME: find out how to do replacements for molecule that support default
    #        values of '{}'
    - name: Patch ansible variables that should default to empty dict
      ansible.builtin.set_fact:
        ingress_traefik_certificates_resolvers: "{{ ingress_traefik_certificates_resolvers or {} }}"
        ingress_traefik_environment_variables: "{{ ingress_traefik_environment_variables or {} }}"
        ingress_traefik_secrets: "{{ ingress_traefik_secrets or {} }}"

    - name: Setup everything
      ansible.builtin.import_role:
        name: benschubert.infrastructure.main

    - name: Get the Grafana group info
      benschubert.infrastructure.authentik_group_info:
        authentik_token: "{{ auth_authentik_token }}"
        authentik_url: https://{{ auth_authentik_hostname }}:{{ ingress_https_port }}
        ca_path: "{{ ingress_custom_ca_cert | default(omit) }}"
        validate_certs: "{{ ingress_validate_certs }}"
        name: "{{ monitoring_grafana_admin_group_name }}"
      register: group

    - name: Get the akadmin user info
      benschubert.infrastructure.authentik_user_info:
        authentik_token: "{{ auth_authentik_token }}"
        authentik_url: https://{{ auth_authentik_hostname }}:{{ ingress_https_port }}
        ca_path: "{{ ingress_custom_ca_cert | default(omit) }}"
        validate_certs: "{{ ingress_validate_certs }}"
        username: akadmin
      register: user

    - name: Add akadmin to the grafana admin group
      benschubert.infrastructure.authentik_user_group:
        authentik_token: "{{ auth_authentik_token }}"
        authentik_url: https://{{ auth_authentik_hostname }}:{{ ingress_https_port }}
        ca_path: "{{ ingress_custom_ca_cert | default(omit) }}"
        validate_certs: "{{ ingress_validate_certs }}"
        user_pk: "{{ user.data.pk }}"
        group_pk: "{{ group.data.pk }}"

    - name: Create a token to access services as akadmin
      benschubert.infrastructure.authentik_token:
        authentik_token: "{{ auth_authentik_token }}"
        authentik_url: https://{{ auth_authentik_hostname }}:{{ ingress_https_port }}
        ca_path: "{{ ingress_custom_ca_cert | default(omit) }}"
        validate_certs: "{{ ingress_validate_certs }}"
        token:
          identifier: molecule-test
          intent: app_password
          user: "{{ user.data.pk }}"
          description: A token to allow Akadmin to access services via APIs
          expiring: false

    ##
    # Example on how to connect a node-exporter to mimir deployed this way
    ##
    - name: Install alloy on the host and configure it
      block:
        - name: Install grafana apt gpg signing key
          become: true
          ansible.builtin.get_url:
            url: https://apt.grafana.com/gpg.key
            dest: /etc/apt/keyrings/grafana.asc
            mode: "0o400"
          register: _gpg_key

        - name: Dearmor the grafana gpg key
          become: true
          ansible.builtin.command:
            cmd: gpg --dearmor --output /etc/apt/keyrings/grafana.gpg /etc/apt/keyrings/grafana.asc
          when: _gpg_key.changed
          changed_when: true
          tags:
            - skip_ansible_lint

        - name: Add grafana apt repository
          become: true
          ansible.builtin.apt_repository:
            repo: deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main
            state: present
            filename: grafana

        - name: Install alloy
          become: true
          ansible.builtin.apt:
            name: alloy

        - name: Create the agent's service account to authenticate
          benschubert.infrastructure.authentik_user:
            authentik_token: "{{ auth_authentik_token }}"
            authentik_url: https://{{ auth_authentik_hostname }}:{{ ingress_https_port }}
            ca_path: "{{ ingress_custom_ca_cert | default(omit) }}"
            validate_certs: "{{ ingress_validate_certs }}"
            user:
              name: host-metrics
              username: host-metrics
              path: service-accounts
              type: service_account
          register: _service_account

        - name: Create the agent's service account's token
          benschubert.infrastructure.authentik_token:
            authentik_token: "{{ auth_authentik_token }}"
            authentik_url: https://{{ auth_authentik_hostname }}:{{ ingress_https_port }}
            ca_path: "{{ ingress_custom_ca_cert | default(omit) }}"
            validate_certs: "{{ ingress_validate_certs }}"
            token:
              identifier: host-metrics-agent-auth-token
              intent: app_password
              user: "{{ _service_account.data.pk }}"
              description: Token to authenticate the agent against mimir
              expiring: false

        - name: Retrieve the generated token
          benschubert.infrastructure.authentik_token_value:
            authentik_token: "{{ auth_authentik_token }}"
            authentik_url: https://{{ auth_authentik_hostname }}:{{ ingress_https_port }}
            ca_path: "{{ ingress_custom_ca_cert | default(omit) }}"
            validate_certs: "{{ ingress_validate_certs }}"
            token: host-metrics-agent-auth-token
          register: _mimir_service_account_token

        - name: Configure alloy
          become: true
          ansible.builtin.template:
            src: config.alloy.j2
            dest: /etc/alloy/config.alloy
            mode: "0o600"
            owner: alloy
            group: alloy
          vars:
            password: "{{ _mimir_service_account_token.key }}"
            username: host-metrics
          register: _alloy_config
          no_log: true

        - name: Ensure alloy is running
          become: true
          ansible.builtin.systemd:
            service: alloy
            state: "{{ 'restarted' if _alloy_config.changed else 'started' }}"
            enabled: true

        - name: Ensure the directory to store alerts exists
          become_method: containers.podman.podman_unshare
          become: true
          ansible.builtin.file:
            name: "{{ monitoring_loki_config_path }}/rules/fake"
            state: directory
            owner: 19218
            group: 19218
            mode: "0o755"

        - name: Install alloy alerts
          become: true
          become_method: containers.podman.podman_unshare
          ansible.builtin.template:
            src: alerts.yml.j2
            dest: "{{ monitoring_loki_config_path }}/rules/fake/node.yml"
            owner: 19218
            group: 19218
            mode: "0o644"
