---
driver:
  name: podman

verifier:
  name: testinfra
  options:
    verbose: true

platforms:
  - name: ${CONTAINER_NAME:-benschubert-infrastructure-test-container}
    image: docker.io/debian:bookworm-slim
    command: /usr/sbin/init
    dockerfile: Dockerfile.j2
    etc_hosts:
      ${AUTHENTIK_HOSTNAME:-auth.test}: 127.0.0.1
      ${TRAEFIK_HOSTNAME:-traefik.test}: 127.0.0.1
      ${GRAFANA_HOSTNAME:-grafana.test}: 127.0.0.1
      ${MIMIR_HOSTNAME:-mimir.test}: 127.0.0.1
    security_opts:
      - label=disable
    published_ports:
      - 127.0.0.1:${HTTP_PORT:-8080}:8080
      - 127.0.0.1:${HTTPS_PORT:-8443}:8443
    devices:
      - /dev/fuse
    privileged: true
    tty: true
    volumes:
      - ${CONTAINER_NAME:-benschubert-infrastructure-test-container}-data:/home/podman/.local/share/containers

provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
  ansible_args:
    - --diff
  env:
    ANSIBLE_PIPELINING: "True"
  inventory:
    host_vars:
      ${CONTAINER_NAME:-benschubert-infrastructure-test-container}:
        ansible_user: podman
        data: /home/podman/infrastructure

        template_warning: |
          ##################################################
          # WARNING
          #
          # This file is managed by ansible.
          #
          # Any change done on this file will be overriden
          # on the next run of ansible.
          ##################################################

        # Hostnames
        auth_authentik_hostname: ${AUTHENTIK_HOSTNAME:-auth.test}
        ingress_traefik_dashboard_hostname: ${TRAEFIK_HOSTNAME:-traefik.test}
        monitoring_grafana_hostname: ${GRAFANA_HOSTNAME:-grafana.test}
        monitoring_mimir_hostname: ${MIMIR_HOSTNAME:-mimir.test}

        ##
        # Ingress
        ##
        ingress_custom_ca_cert_url: ${TRAEFIK_CUSTOM_CA_CERT:-null}
        ingress_http_port: ${HTTP_PORT:-8080}
        ingress_https_port: ${HTTPS_PORT:-8443}
        ingress_monitor_agent_config_path: "{{ data }}/ingress/agent/config"
        ingress_monitor_agent_data_path: "{{ data }}/ingress/agent/data"
        ingress_traefik_certificates_resolvers: ${TRAEFIK_CERTIFICATES_RESOLVER:-null}
        ingress_traefik_configuration_files_path: "{{ data }}/ingress/traefik"
        ingress_traefik_environment_variables: ${TRAEFIK_ENVIRONMENT_VARIABLES:-null}
        ingress_traefik_secrets: ${TRAEFIK_SECRETS:-null}
        ingress_validate_certs: ${TRAEFIK_VALIDATE_CERTS:-false}

        ##
        # Auth
        ##
        auth_authentik_secret_key: verysecretkey
        auth_authentik_superadmin_bootstrap_email: ${AUTHENTIK_EMAIL:-null}
        auth_authentik_superadmin_bootstrap_password: password
        auth_authentik_superadmin_bootstrap_token: superadmintoken
        auth_monitor_agent_config_path: "{{ data }}/auth/agent/config"
        auth_monitor_agent_data_path: "{{ data }}/auth/agent/data"
        auth_postgres_password: verysecretpassword
        auth_postgres_data_path: "{{ data }}/auth/postgres"
        auth_redis_password: veryredispassword
        auth_redis_metrics_password: verymetricspassword
        auth_redis_config_path: "{{ data }}/auth/redis/config/"
        auth_redis_data_path: "{{ data }}/auth/redis/data/"
        auth_authentik_configuration_path: "{{ data }}/auth/authentik"
        auth_authentik_email_config: ${EMAIL_CONFIG:-null}
        auth_authentik_background: ${AUTHENTIK_WALLPAPER:-null}

        ##
        # Monitoring
        ##
        monitoring_grafana_secret_key: averysecretsecret
        monitoring_grafana_admin_user: admin
        monitoring_grafana_admin_bootstrap_password: supersecretpassword
        monitoring_grafana_postgres_password: postgresgrafanapassword
        monitoring_grafana_postgres_data_path: "{{ data }}/monitoring/grafana/postgres"
        monitoring_grafana_data_path: "{{ data }}/monitoring/grafana/grafana"
        monitoring_mimir_config_path: "{{ data }}/monitoring/mimir/config"
        monitoring_mimir_data_path: "{{ data }}/monitoring/mimir/data"
        monitoring_monitor_agent_config_path: "{{ data }}/monitoring/agent/config"
        monitoring_monitor_agent_data_path: "{{ data }}/monitoring/agent/data"
