---
- name: Prepare hosts
  hosts: all
  gather_facts: false

  tasks:
    - name: Gather info about all present pods
      containers.podman.podman_pod_info:
      register: _all_pods

    - name: Remove all current pods and containers
      ansible.builtin.command:
        cmd: podman pod rm {{ _all_pods.pods | map(attribute='Name') | join(' ') }}
      changed_when: true
      when: _all_pods.pods

    - name: Gather info about all present secrets
      ansible.builtin.command:
        cmd: podman secret ls --quiet
      changed_when: false
      register: _all_secrets

    - name: Remove all current secrets
      ansible.builtin.command:
        cmd: podman secret rm {{ _all_secrets.stdout_lines | join(' ') }}
      changed_when: true
      when: _all_secrets.stdout_lines

    - name: Remove leftover files
      become: true
      ansible.builtin.shell:
        cmd: rm -rf /home/podman/infrastructure/*
        removes: /home/podman/infrastructure/*
