---
- name: Prepare hosts
  hosts: all
  gather_facts: false

  tasks:
    - name: Gather info about all present containers
      containers.podman.podman_container_info:
      register: _all_containers

    - name: Remove all current containers
      ansible.builtin.command:
        cmd: podman pod rm {{ _all_containers.containers | map(attribute='Name') | join(' ') }}
      changed_when: true
      when: _all_containers.containers

    - name: Gather info about all present secrets
      ansible.builtin.command:
        cmd: podman secret ls --quiet
      changed_when: false
      register: _all_secrets

    - name: Remove all current secrets
      ansible.builtin.command:
        cmd: podman secret rm {{ _all_secrets.stdout_lines | join(' ') }}
      changed_when: true
      when: _all_secrets.stdout_lines

    - name: Gather info about all present networks
      containers.podman.podman_network_info:
      register: _all_networks

    - name: Remove all current networks
      ansible.builtin.command:
        cmd: >-
          podman
          network
          rm
          {{
            _all_networks.networks
            | map(attribute='name')
            | reject('equalto', 'podman')
            | join(' ')
          }}
      changed_when: true
      when: _all_networks.networks | map(attribute='name') != ["podman"]

    - name: Remove leftover files
      become: true
      ansible.builtin.shell:
        cmd: rm -rf /home/podman/infrastructure/*
        removes: /home/podman/infrastructure/*

    - name: Setup registries
      become: true
      ansible.builtin.copy:
        src: "{{ registries_conf }}"
        dest: /etc/containers/registries.conf.d/050-registries.conf
        mode: "0o755"
      when: registries_conf
