# This file can be copied to a .env.yml at the root of the repo to reproduce

##
# Ports
HTTP_PORT: "80"
HTTPS_PORT: "443"

##
# Group membership
TEST_AKADMIN_USER_GROUP: admins
MONITOR_AGENT_USER_GROUP: metrics-bots
GRAFANA_ADMIN_GROUP_NAME: admins

GRAFANA_ALLOWLISTED_GROUPS: "[admins]"
LOKI_ALLOWLISTED_GROUPS: "[admins]"
MAILPIT_ALLOWLISTED_GROUPS: "[admins]"
MIMIR_ALLOWLISTED_GROUPS: "[admins, metrics-bots]"
TRAEFIK_ALLOWLISTED_GROUPS: "[admins]"
