---
- name: Expand configuration
  ansible.builtin.set_fact:
    ingress_networks: "{{ ingress_networks + ingress_additional_networks }}"
    auth_monitor_agent_user_group: >-
      {{ auth_monitor_agent_user_group or default_monitor_agent_user_group or omit }}
    monitoring_monitor_agent_user_group: >-
      {{ monitoring_monitor_agent_user_group or default_monitor_agent_user_group or omit }}
    ingress_monitor_agent_user_group: >-
      {{ ingress_monitor_agent_user_group or default_monitor_agent_user_group or omit }}

- name: Validate configuration
  ansible.builtin.assert:
    that:
      - auth_authentik_token is not none
    fail_msg: >
      'auth_authentik_token' is none and no
      'auth_authentik_superadmin_bootstrap_token' has been provided

- name: Setup Ingress
  ansible.builtin.import_role:
    name: benschubert.infrastructure.ingress

- name: Setup Auth
  ansible.builtin.import_role:
    name: benschubert.infrastructure.auth

- name: Configure monitoring services
  ansible.builtin.import_role:
    name: benschubert.infrastructure.monitoring

- name: Add Traefik dashboard
  ansible.builtin.import_role:
    name: benschubert.infrastructure.ingress
    tasks_from: finalize
