---
- name: Ensure the PostgreSQL database path exists for {{ postgres_database }}
  become_method: containers.podman.podman_unshare
  become: true
  ansible.builtin.file:
    path: "{{ postgres_data_path }}"
    state: directory
    mode: "0o700"

- name: Create the PostgreSQL network for {{ postgres_database }}
  containers.podman.podman_network:
    name: "{{ postgres_network }}"
    internal: true

- name: Create the PostgreSQL pod for {{ postgres_database }}
  containers.podman.podman_pod:
    name: "{{ postgres_pod }}"
    state: created
    infra_name: "{{ postgres_pod }}-infra"
    network:
      - "{{ postgres_network }}"
    userns: auto:size=1000

- name: Setup a PostgreSQL container for {{ postgres_database }}
  containers.podman.podman_container:
    name: "{{ postgres_pod }}-postgres"
    pod: "{{ postgres_pod }}"
    image: "{{ postgres_image }}"
    user: postgres
    state: started
    volumes:
      - "{{ postgres_data_path }}:/var/lib/postgresql/data:rw,U,Z"
    env:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_DB: "{{ postgres_database }}"
    secrets:
      - "{{ postgres_password_secret }},target=/run/secrets/postgres-password"
    healthcheck: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
    pull: newer
    read_only: true
    cap_drop: [all]
    shm_size: 256m
    tmpfs:
      /var/run: rw

- name: Ensure the PostgreSQL container is healthy for {{ postgres_database }}
  ansible.builtin.command: podman healthcheck run {{ postgres_pod }}-postgres
  register: _healthcheck
  until: _healthcheck is not failed
  retries: 3
  changed_when: false

- name: Install Postgres dashboard for {{ postgres_database }}
  ansible.builtin.import_role:
    name: benschubert.infrastructure.monitoring
    tasks_from: dashboard
  vars:
    content: >-
      {{
        lookup(
          'ansible.builtin.url',
          'https://grafana.com/api/dashboards/455/revisions/latest/download',
          split_lines=False,
        )
        | regex_replace("\${DS_PROMETHEUS}", "mimir")
        | from_json
        | to_json(indent=4)
      }}
    destination: postgres/postgres-overview.json
